### ISSUE TITLE
Disaggregate REDD n UK DALE and VLC LED data

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#12]
Disaggregate a smart mater in REDD n UK DALE and VLC LED data (figure 7b in the iLED paper)

Input
- UK DALE and REDD dataset
- iLED eval scripts/ac/

Note that the VLC LED data needs to be extended to 1s

**Comment by bontorhumala** [comment]
Simple filter from far away:
<img width="842" alt="redd with iled decomposed" src="https://cloud.githubusercontent.com/assets/943854/24044401/734ec3d4-0b1b-11e7-9c44-fea15e084970.PNG">

Simple filter actually does not work:
<img width="859" alt="redd with iled decomposed zoom" src="https://cloud.githubusercontent.com/assets/943854/24044409/786429d6-0b1b-11e7-9ceb-ebe57bf2781c.PNG">

**Comment by bontorhumala** [comment]
FFT Plots
REDD Fs FFT = 30kHz:
<img width="368" alt="fft apps_trace" src="https://cloud.githubusercontent.com/assets/943854/24050482/3b03f8aa-0b2f-11e7-8b23-6836599a7afe.PNG">

iLED Current Fs FFT = 20kHz:
<img width="371" alt="fft ext_current_processed" src="https://cloud.githubusercontent.com/assets/943854/24050484/3b0570f4-0b2f-11e7-917d-af658308cf49.PNG">

adc_processed Fs FFT = 20kHz:
<img width="402" alt="fft adc_processed" src="https://cloud.githubusercontent.com/assets/943854/24050483/3b048838-0b2f-11e7-8c18-d1e408be4f43.PNG">

**Comment by bontorhumala** [comment]
Separating signals:
- Inverse bandpass
- BSS (blind source separation)

**Comment by bontorhumala** [comment]
Highpass, cutoff 1kHz
<img width="811" alt="response" src="https://cloud.githubusercontent.com/assets/943854/24093422/07983fe0-0d54-11e7-8ff3-eebe6d3e0fc3.PNG">
<img width="843" alt="highpass" src="https://cloud.githubusercontent.com/assets/943854/24093421/07968cfe-0d54-11e7-9694-bbc555a5b567.PNG">

Highpass, cutoff 60Hz
<img width="822" alt="response-low" src="https://cloud.githubusercontent.com/assets/943854/24093507/707fe080-0d54-11e7-8507-4954b94b58bc.PNG">
<img width="848" alt="highpass-low" src="https://cloud.githubusercontent.com/assets/943854/24093506/7069c8e0-0d54-11e7-91fb-0d5c1f4827cd.PNG">

**Comment by bontorhumala** [comment]
Bandstop (fc1 40Hz, fc2 60Hz)
<img width="820" alt="bandstop-resp" src="https://cloud.githubusercontent.com/assets/943854/24093586/e2fa73e6-0d54-11e7-9971-7091849afafc.PNG">
<img width="845" alt="bandstop" src="https://cloud.githubusercontent.com/assets/943854/24093587/e2fe5ab0-0d54-11e7-8f74-b46def88099c.PNG">

**Comment by bontorhumala** [comment]
Note: high amplitude is OK (assume)
- Try generate own VLC LED (Arduino iLED, Matlab gold codes, random high frequency 1/0 signal)
- Try one appliance
- BSS
- Discuss w/Angga

**Comment by bontorhumala** [comment]
Implement FFT based filtering on raw adc values and retrieve the LED signals using IFFT

![hilo disag v2](https://cloud.githubusercontent.com/assets/943854/24104311/302a021c-0d82-11e7-9d70-604180417981.png)

**Comment by bontorhumala** [comment]
Using highpass and bandpass with the processed ADC data
<img width="842" alt="hp 1k 1k5 hz 50x" src="https://cloud.githubusercontent.com/assets/943854/24185045/5dc126a6-0ed1-11e7-90a1-3e1c37d1bf59.PNG">
<img width="832" alt="hp 1k 1k5 hz 10x" src="https://cloud.githubusercontent.com/assets/943854/24185044/5dbe91ac-0ed1-11e7-9c0e-1d259ef06ea8.PNG">
<img width="844" alt="hp 1k 1k5 hz 5x" src="https://cloud.githubusercontent.com/assets/943854/24185046/5dc3304a-0ed1-11e7-9e3c-aca6cdd523bb.PNG">


Using highpass and bandpass with the raw ADC data
<img width="850" alt="hilo5 on raw data" src="https://cloud.githubusercontent.com/assets/943854/24184994/0666ec92-0ed1-11e7-8c19-4cf04f670a86.PNG">
<img width="850" alt="hilo5 on raw data zom" src="https://cloud.githubusercontent.com/assets/943854/24184992/0663bce8-0ed1-11e7-98c3-c43c35e4b5a6.PNG">

Using fft + zeroing out apps freq component with the raw ADC data
<img width="842" alt="hilo 6 zoom" src="https://cloud.githubusercontent.com/assets/943854/24184993/0665eb4e-0ed1-11e7-9574-2ab3ff347fa7.PNG">

**Comment by bontorhumala** [comment]
- Do the FFT-IFFT for processed ADC data. How good?
- Binarize for the high pass processed ADC data, just to see

Option 1/2, use 40-60 Hz filter
- Do option 1 for raw/unprocessed ADC data
- Do option 2 for raw/unprocessed ADC data

**Comment by bontorhumala** [comment]
Applying FFT-IFFT filter for processed ADC data

Threshold 0.005, works best on raw (unprocessed) ADC data
![thres 0005](https://ibb.co/ha0f1F)

Threshold 0.01
![thres 001](https://ibb.co/na9waa)

Threshold 0.001
![thres 0001](https://ibb.co/iXHhFa)

**Comment by akshay-sn** [comment]
@bontor: could you round off the value and see if it resembles the original

**Comment by bontorhumala** [comment]
Okay. Btw I tried the FFT IFFT thing on the raw data. Previously, I remove every frequency components that are in the appliances signal. This time, I keep those which are also in the VLC LED signal (e.g. if the 100Hz signal is in both the appliances signal AND in the VLC LED signal, I keep it. If its only in the appliances signal, I remove it). The result is even better.

Threshold 0.005
![keep 0005](https://preview.ibb.co/my9XgF/hilo_6_keep_0005.png)

**Comment by akshay-sn** [comment]
This looks nice. Try option1/2 to see if we can get the proper one.

**Comment by bontorhumala** [comment]
Roundoff to a set of vectors

Threshold 0.005
<img width="841" alt="hilo6 roundoff thres 0005" src="https://cloud.githubusercontent.com/assets/943854/24240761/0342b7a2-0fb3-11e7-8795-3ac44396e45f.PNG">

Threshold 0.001
<img width="845" alt="hilo6 roundoff thres 0001" src="https://cloud.githubusercontent.com/assets/943854/24240762/0346b01e-0fb3-11e7-9dd6-a55d657ad0bb.PNG">

**Comment by akshay-sn** [comment]
This looks great

**Comment by bontorhumala** [comment]
Option 2

Threshold 0.005
<img width="830" alt="hilo7 cutmirr thres 0005" src="https://cloud.githubusercontent.com/assets/943854/24244639/127a2c3e-0fc0-11e7-805f-c5f1f9c34fdd.PNG">

**Comment by bontorhumala** [comment]
- Measure the work on the processed data (Jaccard, Pearson coefficient)

On the unprocessed data:
- Try to fix the flipping thing
- Try option 1

Threshold definition: if the amplitude of appliances signal on that frequency band is higher, that frequency band is removed (unless the VLC LED signal also exists on that freq band)

**Comment by bontorhumala** [comment]
FFT-IFFT on the processed data,
- Jaccard similarity: 0.079733 (close to 0, means similar)
- Pearson correlation coefficient: 0.9556 (close to 1, means linearly correlated)

**Comment by akshay-sn** [comment]
That is very good. Now try to see option 1, if that works we are there almost

**Comment by bontorhumala** [comment]
Working on raw ADC data with option 2, 0.001 threshold. The problem is that its difficult to decide when to mirror -> cannot use threshold (no guarantee that < 4 means inverted and the phase sometimes change in the middle)
 
<img width="850" alt="hilo7 cutmirr thres 0001 marked" src="https://cloud.githubusercontent.com/assets/943854/24285479/84edcdce-1070-11e7-8ebd-46c225d2cd42.PNG">

**Comment by bontorhumala** [comment]
Option 1, threshold 0.001. Frequencies that need to be removed cannot be obtained from appliances trace (i.e. cutting and mirroring change the frequency response of the signal).

<img width="857" alt="hilo8 thres 0001" src="https://cloud.githubusercontent.com/assets/943854/24286270/c2794a70-1074-11e7-9ee4-3fd9f7063239.PNG">

FFT of all traces:
<img width="612" alt="fft hilo8" src="https://cloud.githubusercontent.com/assets/943854/24286280/cfa2c8f2-1074-11e7-8d6a-6965ec73bb1b.PNG">

**Comment by bontorhumala** [comment]
- Make sure the IFFT and ground truth is synced (cut accordingly)
- Check FFT window size in order to discard head and tail errors
- Use BER for metrics
- resiliency of gold code to BER (correlation between mathematical gold codes, only-LEDs data, and aggregated data)
- training: simulate LED signals and obtain potential frequencies (see if there is any pattern in the FFT of unprocessed, processed, and simulated signals)

**Comment by bontorhumala** [comment]
Disaggregation finished, working on above improvements now
