### ISSUE TITLE
Sync trigger and check FFT window size

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#20]
Make the FFT-IFFT result as good as possible by

- Sync trigger 
- Check FFT window size
- Quantize processed data and cut accordingly

**Comment by bontorhumala** [comment]
Fix FFT window size to 2^N (65536 samples to obtain filtered frequencies, previously not 2^N samples)

Result:
<img width="842" alt="hilo7 window 2pn synced" src="https://cloud.githubusercontent.com/assets/943854/24322418/613f4732-1164-11e7-81b5-034dd34c6a99.PNG">

- Jaccard similarity: 2.134e-05 (close to 0, similar)
- Pearson coefficient: 1 (perfectly correlated)

This result now makes sense since every frequencies indeed are kept (tested againts training data)

**Comment by bontorhumala** [comment]
Ground truth code is now quantized, now the disaggregation result is perfectly similar to the ground truth

<img width="838" alt="hilo7 window 2pn synced quantized" src="https://cloud.githubusercontent.com/assets/943854/24322480/5ea9c12c-1165-11e7-9cd7-6c89fd3f8ee4.PNG">

- Jaccard similarity: 2.134e-05 (close to 0, similar)
- Pearson coefficient: 1 (perfectly correlated)

**Comment by bontorhumala** [comment]
@akshay-sn I implement all suggestions from yesterday (fix FFT window, quantize the ground truth, sync the ground truth code to ground truth raw). The result is perfect disaggregation. Shall I proceed to the training thing first? Because in this case, measuring BER and checking resiliency will not make sense, right? i.e our disaggregation result is a perfect clone of Johnny's ground truth

**Comment by akshay-sn** [comment]
Yes, go ahead with training thing and then we can indeed do an experiment
with BER

**Comment by bontorhumala** [comment]
Okay. Im closing this issue then
