### ISSUE TITLE
Train to obtain potential frequencies

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#22]
Simulate LED signals and obtain potential frequencies (see if there is any pattern in the FFT of unprocessed, processed, and simulated signals)

**Comment by bontorhumala** [comment]
@akshay-sn the gold code generator you mentioned on yesterday meeting, is that the Arduino code that you sent last week?

**Comment by akshay-sn** [comment]
NO. I sent you another email with matlab codes

**Comment by bontorhumala** [comment]
Trying to remove appliances frequencies using thresholding. I do not keep ground truth frequencies (i.e. no training is needed)

<img width="840" alt="hilo7 apps thresholding" src="https://cloud.githubusercontent.com/assets/943854/24329871/e19b0fa2-1212-11e7-87d0-1b56df60a665.PNG">

- Jaccard similarity: 0.14937
- Pearson coeff: 0.9238

**Comment by bontorhumala** [comment]
Simulated gold codes (65 LEDs, probability of simultaneous activation 0.5) and ground truth gold codes frequency response. The frequency response does not look similar

<img width="839" alt="gt gc and sim gc" src="https://cloud.githubusercontent.com/assets/943854/24329954/8ea663ee-1214-11e7-8200-719dd7f94020.PNG">

Therefore, keeping the simulated/training frequencies result in bad FFT-IFFT filter output
<img width="840" alt="hilo9" src="https://cloud.githubusercontent.com/assets/943854/24330018/d8af1908-1215-11e7-98eb-8e662d394803.PNG">
