### ISSUE TITLE
Align appliances signal and raw ground truth signal

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#27]
- Same zero Y-axis reference point: find the middle point between peaks in the raw ground truth
- Align phase (X-axis): find the middle of the first trigger (t=4.5 ms), then shift the appliances signal so that the first zero crossing (positive to negative, same as the raw ground truth) also happens at t=4.5 ms

**Comment by bontorhumala** [comment]
Difficult to exactly align the phase. Result with 5ms shift on the appliances signal:

<img width="854" alt="output shift 5ms" src="https://cloud.githubusercontent.com/assets/943854/24365873/a6e91100-1317-11e7-8567-9a5732cc65d8.PNG">
<img width="851" alt="corr shift 5ms" src="https://cloud.githubusercontent.com/assets/943854/24365872/a6e2451e-1317-11e7-86a7-ef14ceffd1b0.PNG">

**Comment by bontorhumala** [comment]
Result with 6ms shift on the appliances signal:

<img width="861" alt="output shift 6ms" src="https://cloud.githubusercontent.com/assets/943854/24366226/c1063e4a-1318-11e7-88d3-3ec00d537e79.PNG">
<img width="872" alt="corr shift 6ms" src="https://cloud.githubusercontent.com/assets/943854/24366227/c106c3e2-1318-11e7-9da5-2bef24ab08a7.PNG">

**Comment by akshay-sn** [comment]
this looks bad right? the fft-ifft is not similar

**Comment by bontorhumala** [comment]
@akshay-sn Maybe it doesnt look similar because the signal is shorter now. The previous https://github.com/bontorhumala/hilo-disaggregator/issues/22 result is also like this.

The BER is low (<0.1) and the F1-score is also good (able to detect the ON state of LED 0) as shown in https://github.com/bontorhumala/hilo-disaggregator/issues/28

I also plot the result using the best threshold (looking at the BER plot in https://github.com/bontorhumala/hilo-disaggregator/issues/28) which is 0.0175, as follow:

<img width="844" alt="output thres 00175" src="https://cloud.githubusercontent.com/assets/943854/24376214/64782f80-133b-11e7-8247-28e51b6cb94d.PNG">
<img width="859" alt="corr thres 00175" src="https://cloud.githubusercontent.com/assets/943854/24376215/648051d8-133b-11e7-9209-dbf6d591df85.PNG">

**Comment by bontorhumala** [comment]
Extrapolate the appliances signal
