### ISSUE TITLE
Investigate the resiliency with different thresholds

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#28]
In case the correct threshold is not used, how bad will the correlation analysis be?

**Comment by akshay-sn** [comment]
correlation, F1 and BER.

**Comment by bontorhumala** [comment]
<img width="858" alt="resiliency w diff threshold" src="https://cloud.githubusercontent.com/assets/943854/24369661/0760df56-1325-11e7-82dc-76de687a4776.PNG">

**Comment by bontorhumala** [comment]
Added correlation on the second subplot

![image](https://cloud.githubusercontent.com/assets/943854/24375808/f8dc34fc-1339-11e7-8600-469f6758f84b.png)
