### ISSUE TITLE
Try on a several appliances and make a script for these appliances

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#29]
Use high frequency appliance data from the COOLL dataset (REDD does not have HF appliance dataset)

**Comment by bontorhumala** [comment]
Washing machine
![image](https://cloud.githubusercontent.com/assets/943854/24379069/b42be8f0-1345-11e7-96c0-46dba44948c4.png)
![image](https://cloud.githubusercontent.com/assets/943854/24379086/c78b0c82-1345-11e7-928a-52ca147c1394.png)

FFT of washing machine trace and raw ground truth
![image](https://cloud.githubusercontent.com/assets/943854/24379167/15f27e96-1346-11e7-8e0a-4a9ed11654a9.png)

Maybe because of resampling?

**Comment by bontorhumala** [comment]
Frequency response without resampling
![image](https://cloud.githubusercontent.com/assets/943854/24379329/f159d920-1346-11e7-9724-96ff8169b3b0.png)

**Comment by bontorhumala** [comment]
In this case, it is important to use low threshold and keep frequencies of LED (training method). See https://github.com/bontorhumala/hilo-disaggregator/issues/21

**Comment by akshay-sn** [comment]
What's the sampling frequency of washing machine data. Before looking at
individual appliances can we try aggregated data from an another dataset
and test the algorithm again.

Also in the fog it does not look very synchronised

**Comment by bontorhumala** [comment]
The sampling frequency is 30kHz. The period is different (the washing
machine is shorter and therefore its difficult to align the phase). Okay I
will try from another dataset.

**Comment by bontorhumala** [comment]
See https://github.com/bontorhumala/hilo-disaggregator/pull/37

**Comment by bontorhumala** [comment]
**Fridge**
FFT-IFFT filter output
![image](https://cloud.githubusercontent.com/assets/943854/24457448/99210278-1496-11e7-82db-71bdd61038ab.png)

Gold code correlation
![image](https://cloud.githubusercontent.com/assets/943854/24457476/ac889d8a-1496-11e7-8455-f2a3a781c50f.png)

**Air conditioner**
FFT-IFFT filter output
![image](https://cloud.githubusercontent.com/assets/943854/24457687/38dfba5c-1497-11e7-96bb-1a96085ff119.png)

Gold code correlation
![image](https://cloud.githubusercontent.com/assets/943854/24457666/2e8fe720-1497-11e7-8dbf-f186c279d6e8.png)

**Hairdryer**
FFT-IFFT filter output
![image](https://cloud.githubusercontent.com/assets/943854/24457779/6c79d1e0-1497-11e7-929b-086310f43ca8.png)

Gold code correlation
![image](https://cloud.githubusercontent.com/assets/943854/24457804/7f218b6c-1497-11e7-886b-2202f71ae48a.png)

**Heater**
FFT-IFFT filter output
![image](https://cloud.githubusercontent.com/assets/943854/24457874/b65eeff2-1497-11e7-8481-b57ef5ba21ac.png)

Gold code correlation
![image](https://cloud.githubusercontent.com/assets/943854/24457847/a1178abe-1497-11e7-8897-afc9453947f4.png)

**Microwave**
FFT-IFFT filter output
![image](https://cloud.githubusercontent.com/assets/943854/24457974/f33fe142-1497-11e7-80b1-d158293c9ae2.png)

Gold code correlation
![image](https://cloud.githubusercontent.com/assets/943854/24457946/e32a436a-1497-11e7-81c6-9c019b042025.png)
