### ISSUE TITLE
Figures for submission and a script to generate these figures

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#33]
As discussed today, here are figures that are required:

- Merging of appliances and ground truth raw (plot 1 in merging - fft ifft output, cut and mirror output.fig)
- FFT plot of appliances, ground truth raw, and combined trace (fft appliances.fig, fft raw ground truth and appliances data.fig, fft raw ground truth.fig)
- FFT and IFFT filtering output (plot 2 in merging - fft ifft output, cut and mirror output.fig)
- Processed ground truth and disaggregated LED result (plot 3 in merging - fft ifft output, cut and mirror output.fig)
- Codes correlation plot (correlation plot.fig)
- Resiliency against different FFT threshold (resilience - ber plot with different threshold.fig; resilience - Pearson corr plot with different threshold.fig)

See https://github.com/bontorhumala/hilo-disaggregator/tree/master/matlab%20figures/paper%20submission

**Comment by bontorhumala** [comment]
@akshay-sn please find required figures in the link above

**Comment by akshay-sn** [comment]
It would be great, if we have one script which can generate the above
figures sequentially. what do you think. Also, could you comment this
script as to which part generates what image./

**Comment by bontorhumala** [comment]
Created README. This will help in generating figures

**Comment by bontorhumala** [comment]
Done, see https://github.com/bontorhumala/hilo-disaggregator/pull/39
